/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db_mhs;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        nim = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        agama = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        enim = new javax.swing.JTextField();
        enama = new javax.swing.JTextField();
        cbagama = new javax.swing.JComboBox<>();
        hasil = new javax.swing.JTextField();
        rb_si = new javax.swing.JRadioButton();
        rb_ti = new javax.swing.JRadioButton();
        hasilo = new javax.swing.JTextField();
        cdmembaca = new javax.swing.JCheckBox();
        cbmenulis = new javax.swing.JCheckBox();
        cbmenonton = new javax.swing.JCheckBox();
        cbrebahan = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bgresume = new javax.swing.JTextArea();
        bgclear = new javax.swing.JButton();
        bgexit = new javax.swing.JButton();
        bgproses = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nim.setText("NoMhs");

        nama.setText("NAMA");

        jLabel3.setText("JURUSAN");

        agama.setText("AGAMA");

        jLabel5.setText("HOBY");

        cbagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katolik", "Hindu", "Buddha", " " }));
        cbagama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbagamaActionPerformed(evt);
            }
        });

        rb_si.setText("SI");

        rb_ti.setText("TI");

        cdmembaca.setText("Membaca");

        cbmenulis.setText("Menulis");

        cbmenonton.setText("Menonton");

        cbrebahan.setText("Rebahan");

        jLabel1.setText("Resume");

        bgresume.setColumns(20);
        bgresume.setRows(5);
        jScrollPane1.setViewportView(bgresume);

        bgclear.setText("Clear");
        bgclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgclearActionPerformed(evt);
            }
        });

        bgexit.setText("Exit");
        bgexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgexitActionPerformed(evt);
            }
        });

        bgproses.setText("Proses");
        bgproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgprosesActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NoMhs", "NAMA", "JURUSAN", "AGAMA", "HOBY"
            }
        ));
        tabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(bgclear, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(bgexit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(bgproses)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(rb_ti, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rb_si, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(hasilo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(enama, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(enim))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbmenulis)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbrebahan))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cdmembaca)
                                        .addGap(27, 27, 27)
                                        .addComponent(cbmenonton))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbagama, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nim)
                        .addComponent(enim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama)
                            .addComponent(enama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rb_ti)
                            .addComponent(rb_si)
                            .addComponent(hasilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agama)
                            .addComponent(cbagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cdmembaca)
                            .addComponent(cbmenonton)
                            .addComponent(jLabel5)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmenulis)
                    .addComponent(cbrebahan))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bgclear)
                    .addComponent(bgexit)
                    .addComponent(bgproses))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bgclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgclearActionPerformed
        // TODO add your handling code here
        enim.setText("");
        enama.setText("");
        hasil.setText("");
        hasilo.setText("");
        bgresume.setText("");
    }//GEN-LAST:event_bgclearActionPerformed

    private void bgexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgexitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bgexitActionPerformed

    private void bgprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgprosesActionPerformed
        // TODO add your handling code here:
        int indexccombo;
        String pilihan;
        String jurusan;
        String daftarhoby="";
        
        indexccombo = cbagama.getSelectedIndex();
        pilihan = (String) cbagama.getSelectedItem();
        
        hasil.setText(pilihan);
        
        jurusan = "Teknik Informatika";
        
        if (rb_si.isSelected()){
            jurusan = "Sistem Informasi";
        }
        else{
            jurusan = "Teknik Informatika";
        }
        
        hasilo.setText(String.valueOf(jurusan));
        
        if(cbmenonton.isSelected())
            daftarhoby+=cbmenonton.getText()+"\n";
        if(cbmenulis.isSelected())
            daftarhoby+=cbmenulis.getText()+"\n";
        if(cbrebahan.isSelected())
            daftarhoby+=cbrebahan.getText()+"\n";
        if(cdmembaca.isSelected())
            daftarhoby+=cdmembaca.getText()+"\n";
      bgresume.setText(
        "NoMhs  :\t"+enim.getText()+"\n"+
        "NAMA   :\t"+enama.getText()+"\n"+
        "JURUSAN:\t"+jurusan+"\n"+
        "AGAMA  :\t"+pilihan+"\n"+
        "HOBY   :\t"+daftarhoby);
    }//GEN-LAST:event_bgprosesActionPerformed

    private void cbagamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbagamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbagamaActionPerformed

    private void tabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelAncestorAdded

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseClicked

    /**
     * @param args the command line arguments int indexccombo;
        String pilihan;
        String jurusan;
        String daftarhoby="";
        
        indexccombo = cbagama.getSelectedIndex();
        pilihan = (String) cbagama.getSelectedItem();
        
        hasil.setText(pilihan);
        
        jurusan = "Teknik Informatika";
        
        if (rb_si.isSelected()){
            jurusan = "Sistem Informasi";
        }
        else{
            jurusan = "Teknik Informatika";
        }
        
        hasilo.setText(String.valueOf(jurusan));
        
        if(cbmenonton.isSelected())
            daftarhoby+=cbmenonton.getText()+"\n";
        if(cbmenulis.isSelected())
            daftarhoby+=cbmenulis.getText()+"\n";
        if(cbrebahan.isSelected())
            daftarhoby+=cbrebahan.getText()+"\n";
        if(cdmembaca.isSelected())
            daftarhoby+=cdmembaca.getText()+"\n";
      bgresume.setText(
        "NoMhs  :\t"+enim.getText()+"\n"+
        "NAMA   :\t"+enama.getText()+"\n"+
        "JURUSAN:\t"+jurusan+"\n"+
        "AGAMA  :\t"+pilihan+"\n"+
        "HOBY   :\t"+daftarhoby);
    }                                   
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agama;
    private javax.swing.JButton bgclear;
    private javax.swing.JButton bgexit;
    private javax.swing.JButton bgproses;
    private javax.swing.JTextArea bgresume;
    private javax.swing.JComboBox<String> cbagama;
    private javax.swing.JCheckBox cbmenonton;
    private javax.swing.JCheckBox cbmenulis;
    private javax.swing.JCheckBox cbrebahan;
    private javax.swing.JCheckBox cdmembaca;
    private javax.swing.JTextField enama;
    private javax.swing.JTextField enim;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField hasilo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nim;
    private javax.swing.JRadioButton rb_si;
    private javax.swing.JRadioButton rb_ti;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
